-- Generated by scripts/generate-flight-history-sql.mjs. Do not edit by hand.

-- Source rows: 119; unique flights: 115; skipped duplicates: 79 (kept 78), 77 (kept 76), 82 (kept 81), 84 (kept 83).

INSERT INTO atlas_airlines (iata_code, icao_code, name, name_zh, country, country_code, callsign, notes)
VALUES
  ('QR', 'QTR', 'Qatar Airways', '卡塔尔航空', 'Qatar', 'QAT', 'Qatari', NULL),
  ('TK', 'THY', 'Turkish Airlines', '土耳其航空', 'Turkey', 'TUR', 'Turkish', NULL),
  ('EK', 'UAE', 'Emirates', '阿联酋航空', 'UAE', 'ARE', 'Emirates', NULL),
  ('MH', 'MAS', 'Malaysia Airlines', '马来西亚航空', 'Malaysia', 'MYS', 'Malaysian', NULL),
  ('AK', 'AXM', 'AirAsia', '亚洲航空', 'Malaysia', 'MYS', 'Red Cap', NULL),
  ('GA', 'GIA', 'Garuda Indonesia', '印尼鹰航', 'Indonesia', 'IDN', 'Indonesia', NULL),
  ('OZ', 'AAR', 'Asiana Airlines', '韩亚航空', 'Korea, Republic of', 'KOR', 'Asiana', NULL),
  ('AF', 'AFR', 'Air France', '法国航空', 'France', 'FRA', 'Airfrans', NULL),
  ('AA', 'AAL', 'American Airlines', '美国航空', 'United States', 'USA', 'American', NULL),
  ('KA', 'HDA', 'Cathay Dragon', '港龙航空', 'Hong Kong', 'HKG', 'Dragon', '2020 年已并入国泰，仅供历史航班使用。')
ON CONFLICT(iata_code) DO UPDATE SET
  icao_code = excluded.icao_code,
  name = excluded.name,
  name_zh = excluded.name_zh,
  country = excluded.country,
  country_code = excluded.country_code,
  callsign = excluded.callsign,
  notes = excluded.notes,
  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now');

INSERT INTO atlas_airports (iata_code, icao_code, name, name_zh, city, city_zh, country, country_code, region, latitude, longitude, timezone, elevation_ft, notes)
VALUES
  ('DOH', 'OTHH', 'Hamad International Airport', '多哈哈马德国际机场', 'Doha', '多哈', 'Qatar', 'QAT', NULL, 25.2731, 51.6081, 'Asia/Qatar', 13, NULL),
  ('CMN', 'GMMN', 'Mohammed V International Airport', '卡萨布兰卡穆罕默德五世国际机场', 'Casablanca', '卡萨布兰卡', 'Morocco', 'MAR', NULL, 33.3675, -7.59, 'Africa/Casablanca', 656, NULL),
  ('IST', 'LTFM', 'Istanbul Airport', '伊斯坦布尔机场', 'Istanbul', '伊斯坦布尔', 'Turkey', 'TUR', NULL, 41.2613, 28.7419, 'Europe/Istanbul', 325, NULL),
  ('NBO', 'HKJK', 'Jomo Kenyatta International Airport', '内罗毕焦莫·肯雅塔国际机场', 'Nairobi', '内罗毕', 'Kenya', 'KEN', NULL, -1.3192, 36.9278, 'Africa/Nairobi', 5330, NULL),
  ('DXB', 'OMDB', 'Dubai International Airport', '迪拜国际机场', 'Dubai', '迪拜', 'UAE', 'ARE', NULL, 25.2528, 55.3644, 'Asia/Dubai', 62, NULL),
  ('NCE', 'LFMN', 'Nice Côte d''Azur Airport', '尼斯蔚蓝海岸机场', 'Nice', '尼斯', 'France', 'FRA', NULL, 43.6584, 7.2159, 'Europe/Paris', 12, NULL),
  ('KUL', 'WMKK', 'Kuala Lumpur International Airport', '吉隆坡国际机场', 'Kuala Lumpur', '吉隆坡', 'Malaysia', 'MYS', NULL, 2.7456, 101.7099, 'Asia/Kuala_Lumpur', 70, NULL),
  ('JHB', 'WMKJ', 'Senai International Airport', '新山士乃国际机场', 'Johor Bahru', '新山', 'Malaysia', 'MYS', NULL, 1.6413, 103.6696, 'Asia/Kuala_Lumpur', 135, NULL),
  ('CGK', 'WIII', 'Soekarno-Hatta International Airport', '苏加诺-哈达国际机场', 'Jakarta', '雅加达', 'Indonesia', 'IDN', NULL, -6.1256, 106.6559, 'Asia/Jakarta', 34, NULL),
  ('SIN', 'WSSS', 'Singapore Changi Airport', '新加坡樟宜机场', 'Singapore', '新加坡', 'Singapore', 'SGP', NULL, 1.3644, 103.9915, 'Asia/Singapore', 22, NULL),
  ('DPS', 'WADD', 'Ngurah Rai International Airport', '巴厘岛伍拉·赖国际机场', 'Denpasar', '登巴萨', 'Indonesia', 'IDN', NULL, -8.7482, 115.1672, 'Asia/Makassar', 14, NULL),
  ('ICN', 'RKSI', 'Incheon International Airport', '仁川国际机场', 'Seoul', '首尔', 'Korea, Republic of', 'KOR', NULL, 37.4602, 126.4407, 'Asia/Seoul', 23, NULL),
  ('GMP', 'RKSS', 'Gimpo International Airport', '金浦国际机场', 'Seoul', '首尔', 'Korea, Republic of', 'KOR', NULL, 37.5583, 126.7906, 'Asia/Seoul', 59, NULL),
  ('CDG', 'LFPG', 'Paris Charles de Gaulle Airport', '巴黎夏尔·戴高乐机场', 'Paris', '巴黎', 'France', 'FRA', NULL, 49.0097, 2.5479, 'Europe/Paris', 392, NULL),
  ('FCO', 'LIRF', 'Rome Fiumicino Leonardo da Vinci Airport', '罗马菲乌米奇诺机场', 'Rome', '罗马', 'Italy', 'ITA', NULL, 41.8003, 12.2389, 'Europe/Rome', 13, NULL),
  ('ORD', 'KORD', 'Chicago O''Hare International Airport', '芝加哥奥黑尔国际机场', 'Chicago', '芝加哥', 'United States', 'USA', NULL, 41.9742, -87.9073, 'America/Chicago', 672, NULL),
  ('GVA', 'LSGG', 'Geneva Airport', '日内瓦国际机场', 'Geneva', '日内瓦', 'Switzerland', 'CHE', NULL, 46.2381, 6.109, 'Europe/Zurich', 1411, NULL),
  ('MUC', 'EDDM', 'Munich Airport', '慕尼黑机场', 'Munich', '慕尼黑', 'Germany', 'DEU', NULL, 48.3538, 11.7861, 'Europe/Berlin', 1487, NULL),
  ('NAY', 'ZBNY', 'Beijing Nanyuan Airport', '北京南苑机场', 'Beijing', '北京', 'China', 'CHN', NULL, 39.7825, 116.3878, 'Asia/Shanghai', NULL, '2019 年 9 月已停运，仅供历史航班使用。')
ON CONFLICT(iata_code) DO UPDATE SET
  icao_code = excluded.icao_code,
  name = excluded.name,
  name_zh = excluded.name_zh,
  city = excluded.city,
  city_zh = excluded.city_zh,
  country = excluded.country,
  country_code = excluded.country_code,
  region = excluded.region,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  timezone = excluded.timezone,
  elevation_ft = excluded.elevation_ft,
  notes = excluded.notes,
  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now');

INSERT INTO atlas_flights (
  airline_id, flight_number, flight_date, departure_airport_id, arrival_airport_id,
  journey_id, aircraft_type_id, aircraft_registration, scheduled_departure_local,
  scheduled_arrival_local, cabin_class, seat_number, notes, great_circle_km,
  route_factor, route_distance_km, estimated_hours, formula_version, is_domestic
)
VALUES
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'GJ'),
    '8888', '2026-09-06',
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'HGH'),
    NULL, NULL, NULL, '2026-09-06T10:45', '2026-09-06T13:05',
    NULL, NULL, NULL, 1148.0876269486564, 1.08, 1239.934637104549,
    1.6070494815779273, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'CZ'),
    '5438', '2026-08-30',
    (SELECT id FROM atlas_airports WHERE iata_code = 'YIN'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'PKX'),
    NULL, NULL, NULL, '2026-08-30T15:10', '2026-08-30T19:30',
    NULL, NULL, NULL, 2930.5682217084973, 1.05, 3077.0966327939223,
    3.833979231858396, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'CZ'),
    '5437', '2026-08-22',
    (SELECT id FROM atlas_airports WHERE iata_code = 'PKX'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'YIN'),
    NULL, NULL, NULL, '2026-08-22T09:15', '2026-08-22T14:25',
    NULL, NULL, NULL, 2930.5682217084973, 1.05, 3077.0966327939223,
    3.833979231858396, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'HU'),
    '7678', '2026-08-07',
    (SELECT id FROM atlas_airports WHERE iata_code = 'HGH'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    NULL, NULL, NULL, '2026-08-07T23:05', '2026-08-08T01:20',
    NULL, NULL, NULL, 1148.0876269486564, 1.08, 1239.934637104549,
    1.6070494815779273, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'CA'),
    '1724', '2026-06-29',
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'HGH'),
    NULL, NULL, NULL, '2026-06-29T17:30', '2026-06-29T19:45',
    NULL, NULL, NULL, 1148.0876269486564, 1.08, 1239.934637104549,
    1.6070494815779273, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'HU'),
    '7677', '2026-05-05',
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'HGH'),
    NULL, NULL, NULL, '2026-05-05T18:00', '2026-05-05T20:10',
    NULL, NULL, NULL, 1148.0876269486564, 1.08, 1239.934637104549,
    1.6070494815779273, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'HU'),
    '7678', '2026-04-28',
    (SELECT id FROM atlas_airports WHERE iata_code = 'HGH'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    NULL, NULL, NULL, '2026-04-28T21:25', '2026-04-28T23:40',
    NULL, NULL, NULL, 1148.0876269486564, 1.08, 1239.934637104549,
    1.6070494815779273, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'KN'),
    '5986', '2026-04-03',
    (SELECT id FROM atlas_airports WHERE iata_code = 'HGH'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'PKX'),
    NULL, NULL, NULL, '2026-04-03T19:55', '2026-04-03T22:10',
    NULL, NULL, NULL, 1093.0835763687694, 1.08, 1180.530262478271,
    1.522186089254673, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'HU'),
    '7377', '2026-03-29',
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'HGH'),
    NULL, NULL, NULL, '2026-03-29T22:05', '2026-03-30T00:25',
    NULL, NULL, NULL, 1148.0876269486564, 1.08, 1239.934637104549,
    1.6070494815779273, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'HU'),
    '7678', '2026-03-26',
    (SELECT id FROM atlas_airports WHERE iata_code = 'HGH'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    NULL, NULL, NULL, '2026-03-26T21:10', '2026-03-26T23:45',
    NULL, NULL, NULL, 1148.0876269486564, 1.08, 1239.934637104549,
    1.6070494815779273, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'MU'),
    '5330', '2026-02-28',
    (SELECT id FROM atlas_airports WHERE iata_code = 'CAN'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'SHA'),
    NULL, NULL, NULL, '2026-02-28T19:05', '2026-02-28T21:10',
    NULL, NULL, NULL, 1175.501551569707, 1.08, 1269.5416756952836,
    1.6493452509932625, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'HU'),
    '7017', '2026-02-26',
    (SELECT id FROM atlas_airports WHERE iata_code = 'HAK'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'ZUH'),
    NULL, NULL, NULL, '2026-02-26T08:05', '2026-02-26T09:00',
    NULL, NULL, NULL, 380.48807160740955, 1.12, 426.14664020029875,
    0.5056879841201792, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'CA'),
    '1387', '2026-02-21',
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'SYX'),
    NULL, NULL, NULL, '2026-02-21T09:10', '2026-02-21T13:25',
    NULL, NULL, NULL, 2517.365006265058, 1.05, 2643.2332565783113,
    3.3235517304282656, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'MU'),
    '5134', '2026-01-16',
    (SELECT id FROM atlas_airports WHERE iata_code = 'HGH'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'PKX'),
    NULL, NULL, NULL, '2026-01-16T19:05', '2026-01-16T21:20',
    NULL, NULL, NULL, 1093.0835763687694, 1.08, 1180.530262478271,
    1.522186089254673, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'HU'),
    '7377', '2026-01-02',
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'HGH'),
    NULL, NULL, NULL, '2026-01-02T21:40', '2026-01-03T00:05',
    NULL, NULL, NULL, 1148.0876269486564, 1.08, 1239.934637104549,
    1.6070494815779273, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'HU'),
    '7678', '2025-12-26',
    (SELECT id FROM atlas_airports WHERE iata_code = 'HGH'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    NULL, NULL, NULL, '2025-12-26T21:10', '2025-12-26T23:40',
    NULL, NULL, NULL, 1148.0876269486564, 1.08, 1239.934637104549,
    1.6070494815779273, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'HU'),
    '7603', '2025-12-01',
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'SHA'),
    NULL, NULL, NULL, '2025-12-01T08:25', '2025-12-01T10:35',
    NULL, NULL, NULL, 1075.7074907384954, 1.08, 1161.7640899975752,
    1.4953772714251075, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'HU'),
    '7612', '2025-11-28',
    (SELECT id FROM atlas_airports WHERE iata_code = 'PVG'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    NULL, NULL, NULL, '2025-11-28T19:30', '2025-11-28T22:00',
    NULL, NULL, NULL, 1098.7985704067096, 1.08, 1186.7024560392465,
    1.531003508627495, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'HU'),
    '7603', '2025-10-27',
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'SHA'),
    NULL, NULL, NULL, '2025-10-27T08:25', '2025-10-27T10:35',
    NULL, NULL, NULL, 1075.7074907384954, 1.08, 1161.7640899975752,
    1.4953772714251075, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'JD'),
    '5907', '2025-10-24',
    (SELECT id FROM atlas_airports WHERE iata_code = 'HGH'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'PKX'),
    NULL, NULL, NULL, '2025-10-24T19:45', '2025-10-24T22:10',
    NULL, NULL, NULL, 1093.0835763687694, 1.08, 1180.530262478271,
    1.522186089254673, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'HU'),
    '7277', '2025-10-20',
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'HGH'),
    NULL, NULL, NULL, '2025-10-20T07:55', '2025-10-20T10:15',
    NULL, NULL, NULL, 1148.0876269486564, 1.08, 1239.934637104549,
    1.6070494815779273, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'JD'),
    '5907', '2025-10-17',
    (SELECT id FROM atlas_airports WHERE iata_code = 'HGH'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'PKX'),
    NULL, NULL, NULL, '2025-10-17T19:45', '2025-10-17T22:10',
    NULL, NULL, NULL, 1093.0835763687694, 1.08, 1180.530262478271,
    1.522186089254673, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'HU'),
    '7277', '2025-10-09',
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'HGH'),
    NULL, NULL, NULL, '2025-10-09T08:00', '2025-10-09T10:15',
    NULL, NULL, NULL, 1148.0876269486564, 1.08, 1239.934637104549,
    1.6070494815779273, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'JD'),
    '5907', '2025-09-26',
    (SELECT id FROM atlas_airports WHERE iata_code = 'HGH'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'PKX'),
    NULL, NULL, NULL, '2025-09-26T19:45', '2025-09-26T22:10',
    NULL, NULL, NULL, 1093.0835763687694, 1.08, 1180.530262478271,
    1.522186089254673, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'CA'),
    '1724', '2025-09-06',
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'HGH'),
    NULL, NULL, NULL, '2025-09-06T17:30', '2025-09-06T19:45',
    NULL, NULL, NULL, 1148.0876269486564, 1.08, 1239.934637104549,
    1.6070494815779273, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = '3U'),
    '8884', '2025-07-18',
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'CTU'),
    NULL, NULL, NULL, '2025-07-18T11:40', '2025-07-18T14:30',
    NULL, NULL, NULL, 1558.3425003285777, 1.05, 1636.2596253450067,
    2.1388768701537897, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'CA'),
    '1558', '2025-07-14',
    (SELECT id FROM atlas_airports WHERE iata_code = 'SHA'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    NULL, NULL, NULL, '2025-07-14T15:25', '2025-07-14T17:45',
    NULL, NULL, NULL, 1075.7074907384954, 1.08, 1161.7640899975752,
    1.4953772714251075, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'CA'),
    '1732', '2025-05-05',
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'HGH'),
    NULL, NULL, NULL, '2025-05-05T22:20', '2025-05-06T00:55',
    NULL, NULL, NULL, 1148.0876269486564, 1.08, 1239.934637104549,
    1.6070494815779273, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'CA'),
    '1729', '2025-04-29',
    (SELECT id FROM atlas_airports WHERE iata_code = 'HGH'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    NULL, NULL, NULL, '2025-04-29T21:00', '2025-04-29T23:30',
    NULL, NULL, NULL, 1148.0876269486564, 1.08, 1239.934637104549,
    1.6070494815779273, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'MU'),
    '6161', '2025-02-22',
    (SELECT id FROM atlas_airports WHERE iata_code = 'PKX'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'HGH'),
    NULL, NULL, NULL, '2025-02-22T14:00', '2025-02-22T16:10',
    NULL, NULL, NULL, 1093.0835763687694, 1.08, 1180.530262478271,
    1.522186089254673, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'CA'),
    '1698', '2025-02-17',
    (SELECT id FROM atlas_airports WHERE iata_code = 'DQA'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    NULL, NULL, NULL, '2025-02-17T09:30', '2025-02-17T11:40',
    NULL, NULL, NULL, 1012.0751688999432, 1.08, 1093.0411824119387,
    1.3972016891599126, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'CZ'),
    '5168', '2025-02-10',
    (SELECT id FROM atlas_airports WHERE iata_code = 'NGB'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'HRB'),
    NULL, NULL, NULL, '2025-02-10T07:50', '2025-02-10T10:55',
    NULL, NULL, NULL, 1805.4043109595768, 1.05, 1895.6745265075558,
    2.4440708715214945, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'HU'),
    '7191', '2025-02-06',
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'XMN'),
    NULL, NULL, NULL, '2025-02-06T09:00', '2025-02-06T12:00',
    NULL, NULL, NULL, 1733.1438171804139, 1.05, 1819.8010080394347,
    2.3548079086178224, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'MU'),
    '6162', '2025-01-08',
    (SELECT id FROM atlas_airports WHERE iata_code = 'HGH'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'PKX'),
    NULL, NULL, NULL, '2025-01-08T17:25', '2025-01-08T19:45',
    NULL, NULL, NULL, 1093.0835763687694, 1.08, 1180.530262478271,
    1.522186089254673, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'MU'),
    '6482', '2024-10-07',
    (SELECT id FROM atlas_airports WHERE iata_code = 'KMG'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'HGH'),
    NULL, NULL, NULL, '2024-10-07T06:55', '2024-10-07T09:45',
    NULL, NULL, NULL, 1812.0154575448987, 1.05, 1902.6162304221436,
    2.4522375820092446, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = '3U'),
    '3161', '2024-10-01',
    (SELECT id FROM atlas_airports WHERE iata_code = 'HGH'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'KMG'),
    NULL, NULL, NULL, '2024-10-01T09:30', '2024-10-01T12:30',
    NULL, NULL, NULL, 1812.0154575448987, 1.05, 1902.6162304221436,
    2.4522375820092446, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'HO'),
    '1253', '2024-09-14',
    (SELECT id FROM atlas_airports WHERE iata_code = 'SHA'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'PKX'),
    NULL, NULL, NULL, '2024-09-14T10:55', '2024-09-14T13:05',
    NULL, NULL, NULL, 1025.0127787886156, 1.08, 1107.0138010917049,
    1.4171625729881498, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'CZ'),
    '8860', '2024-06-25',
    (SELECT id FROM atlas_airports WHERE iata_code = 'HGH'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'PKX'),
    NULL, NULL, NULL, '2024-06-25T20:30', '2024-06-25T22:45',
    NULL, NULL, NULL, 1093.0835763687694, 1.08, 1180.530262478271,
    1.522186089254673, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'HO'),
    '1992', '2024-05-20',
    (SELECT id FROM atlas_airports WHERE iata_code = 'TFU'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'HGH'),
    NULL, NULL, NULL, '2024-05-20T15:00', '2024-05-20T17:45',
    NULL, NULL, NULL, 1534.0455158790635, 1.05, 1610.7477916730168,
    2.1088629481867427, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'HO'),
    '1991', '2024-05-17',
    (SELECT id FROM atlas_airports WHERE iata_code = 'HGH'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'TFU'),
    NULL, NULL, NULL, '2024-05-17T13:50', '2024-05-17T16:45',
    NULL, NULL, NULL, 1534.0455158790635, 1.05, 1610.7477916730168,
    2.1088629481867427, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'MU'),
    '9668', '2024-04-07',
    (SELECT id FROM atlas_airports WHERE iata_code = 'PKX'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'HGH'),
    NULL, NULL, NULL, '2024-04-07T18:15', '2024-04-07T20:25',
    NULL, NULL, NULL, 1093.0835763687694, 1.08, 1180.530262478271,
    1.522186089254673, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'CZ'),
    '8858', '2024-01-11',
    (SELECT id FROM atlas_airports WHERE iata_code = 'HGH'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'PKX'),
    NULL, NULL, NULL, '2024-01-11T15:35', '2024-01-11T17:55',
    NULL, NULL, NULL, 1093.0835763687694, 1.08, 1180.530262478271,
    1.522186089254673, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'CZ'),
    '8855', '2023-10-08',
    (SELECT id FROM atlas_airports WHERE iata_code = 'PKX'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'HGH'),
    NULL, NULL, NULL, '2023-10-08T09:15', '2023-10-08T11:15',
    NULL, NULL, NULL, 1093.0835763687694, 1.08, 1180.530262478271,
    1.522186089254673, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'KN'),
    '3028', '2023-08-26',
    (SELECT id FROM atlas_airports WHERE iata_code = 'PKX'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'HGH'),
    NULL, NULL, NULL, '2023-08-26T06:20', '2023-08-26T08:30',
    NULL, NULL, NULL, 1093.0835763687694, 1.08, 1180.530262478271,
    1.522186089254673, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'CZ'),
    '3113', '2023-07-26',
    (SELECT id FROM atlas_airports WHERE iata_code = 'CAN'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'PKX'),
    NULL, NULL, NULL, '2023-07-26T17:00', '2023-07-26T20:15',
    NULL, NULL, NULL, 1815.099952686439, 1.05, 1905.8549503207612,
    2.4560478407135005, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'CZ'),
    '3099', '2023-01-29',
    (SELECT id FROM atlas_airports WHERE iata_code = 'CAN'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'PKX'),
    NULL, NULL, NULL, '2023-01-29T09:00', '2023-01-29T12:00',
    NULL, NULL, NULL, 1815.099952686439, 1.05, 1905.8549503207612,
    2.4560478407135005, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'CZ'),
    '3102', '2023-01-14',
    (SELECT id FROM atlas_airports WHERE iata_code = 'PKX'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'CAN'),
    NULL, NULL, NULL, '2023-01-14T12:30', '2023-01-14T15:45',
    NULL, NULL, NULL, 1815.099952686439, 1.05, 1905.8549503207612,
    2.4560478407135005, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'CZ'),
    '3113', '2019-10-07',
    (SELECT id FROM atlas_airports WHERE iata_code = 'CAN'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    NULL, NULL, NULL, '2019-10-07T17:00', '2019-10-07T20:15',
    NULL, NULL, NULL, 1880.916992238199, 1.05, 1974.962841850109,
    2.5373512425127336, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'CZ'),
    '3152', '2019-09-30',
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'SZX'),
    NULL, NULL, NULL, '2019-09-30T13:00', '2019-09-30T16:25',
    NULL, NULL, NULL, 1956.7680324640012, 1.05, 2054.6064340872013,
    2.631049586321077, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'CA'),
    '1739', '2018-10-05',
    (SELECT id FROM atlas_airports WHERE iata_code = 'HGH'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    NULL, NULL, NULL, '2018-10-05T20:20', '2018-10-05T22:40',
    NULL, NULL, NULL, 1148.0876269486564, 1.08, 1239.934637104549,
    1.6070494815779273, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'CA'),
    '1831', '2018-10-02',
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'SHA'),
    NULL, NULL, NULL, '2018-10-02T07:30', '2018-10-02T09:40',
    NULL, NULL, NULL, 1075.7074907384954, 1.08, 1161.7640899975752,
    1.4953772714251075, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'CA'),
    '1134', '2017-06-26',
    (SELECT id FROM atlas_airports WHERE iata_code = 'UCB'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    NULL, NULL, NULL, '2017-06-26T22:55', '2017-06-27T00:15',
    NULL, NULL, NULL, 316.9688361782642, 1.12, 355.005096519656,
    0.4630030579117936, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'CA'),
    '1133', '2017-06-25',
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'UCB'),
    NULL, NULL, NULL, '2017-06-25T07:00', '2017-06-25T08:20',
    NULL, NULL, NULL, 316.9688361782642, 1.12, 355.005096519656,
    0.4630030579117936, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'CA'),
    '9652', '2017-02-03',
    (SELECT id FROM atlas_airports WHERE iata_code = 'UCB'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    NULL, NULL, NULL, '2017-02-03T00:10', '2017-02-03T01:30',
    NULL, NULL, NULL, 316.9688361782642, 1.12, 355.005096519656,
    0.4630030579117936, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'CA'),
    '9651', '2017-01-31',
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'UCB'),
    NULL, NULL, NULL, '2017-01-31T20:55', '2017-01-31T22:15',
    NULL, NULL, NULL, 316.9688361782642, 1.12, 355.005096519656,
    0.4630030579117936, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'MU'),
    '2443', '2013-07-25',
    (SELECT id FROM atlas_airports WHERE iata_code = 'XNN'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    NULL, NULL, NULL, '2013-07-25T15:50', '2013-07-25T18:05',
    NULL, NULL, NULL, 1328.2969051178857, 1.08, 1434.5606575273166,
    1.8850866536104522, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'MU'),
    '2078', '2013-07-22',
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'XNN'),
    NULL, NULL, NULL, '2013-07-22T10:35', '2013-07-22T13:20',
    NULL, NULL, NULL, 1328.2969051178857, 1.08, 1434.5606575273166,
    1.8850866536104522, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'KN'),
    '2258', '2012-05-20',
    (SELECT id FROM atlas_airports WHERE iata_code = 'CSX'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'NAY'),
    NULL, NULL, NULL, '2012-05-20T14:25', '2012-05-20T16:15',
    NULL, NULL, NULL, 1321.527538429032, 1.08, 1427.2497415033545,
    1.874642487861935, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'KN'),
    '2257', '2012-05-17',
    (SELECT id FROM atlas_airports WHERE iata_code = 'NAY'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'CSX'),
    NULL, NULL, NULL, '2012-05-17T11:30', '2012-05-17T13:35',
    NULL, NULL, NULL, 1321.527538429032, 1.08, 1427.2497415033545,
    1.874642487861935, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'CZ'),
    '3179', '2012-05-02',
    (SELECT id FROM atlas_airports WHERE iata_code = 'CGO'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    NULL, NULL, NULL, '2012-05-02T20:50', '2012-05-02T22:15',
    NULL, NULL, NULL, 663.2480931162503, 1.08, 716.3079405655503,
    0.8590113436650719, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'CA'),
    '1331', '2012-04-29',
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'CGO'),
    NULL, NULL, NULL, '2012-04-29T07:20', '2012-04-29T08:50',
    NULL, NULL, NULL, 663.2480931162503, 1.08, 716.3079405655503,
    0.8590113436650719, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'CA'),
    '1326', '2011-03-13',
    (SELECT id FROM atlas_airports WHERE iata_code = 'CGO'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    NULL, NULL, NULL, '2011-03-13T14:30', '2011-03-13T15:55',
    NULL, NULL, NULL, 663.2480931162503, 1.08, 716.3079405655503,
    0.8590113436650719, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'CA'),
    '1330', '2011-02-11',
    (SELECT id FROM atlas_airports WHERE iata_code = 'CAN'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    NULL, NULL, NULL, '2011-02-11T10:50', '2011-02-11T13:45',
    NULL, NULL, NULL, 1880.916992238199, 1.05, 1974.962841850109,
    2.5373512425127336, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'CA'),
    '1321', '2011-02-04',
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'CAN'),
    NULL, NULL, NULL, '2011-02-04T09:00', '2011-02-04T12:00',
    NULL, NULL, NULL, 1880.916992238199, 1.05, 1974.962841850109,
    2.5373512425127336, 1, 1
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'CZ'),
    '6082', '2025-08-30',
    (SELECT id FROM atlas_airports WHERE iata_code = 'MFM'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'PKX'),
    NULL, NULL, NULL, '2025-08-30T15:55', '2025-08-30T19:10',
    NULL, NULL, NULL, 1947.8509302024856, 1.05, 2045.2434767126101,
    2.62003434235097, 1, 0
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'CZ'),
    '355', '2025-08-23',
    (SELECT id FROM atlas_airports WHERE iata_code = 'PKX'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'HKG'),
    NULL, NULL, NULL, '2025-08-23T08:55', '2025-08-23T12:30',
    NULL, NULL, NULL, 1925.9644748303945, 1.05, 2022.2626985719144,
    2.5929981327736806, 1, 0
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'QR'),
    '892', '2025-08-09',
    (SELECT id FROM atlas_airports WHERE iata_code = 'DOH'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'PKX'),
    NULL, NULL, NULL, '2025-08-09T02:10', '2025-08-09T15:00',
    NULL, NULL, NULL, 6154.390758780863, 1.03, 6339.022481544289,
    7.671539053917651, 1, 0
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'QR'),
    '4566', '2025-08-08',
    (SELECT id FROM atlas_airports WHERE iata_code = 'CMN'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'DOH'),
    NULL, NULL, NULL, '2025-08-08T14:10', '2025-08-08T23:35',
    NULL, NULL, NULL, 5734.449018078061, 1.03, 5906.482488620403,
    7.162668474007197, 1, 0
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'TK'),
    '617', '2025-07-29',
    (SELECT id FROM atlas_airports WHERE iata_code = 'IST'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'CMN'),
    NULL, NULL, NULL, '2025-07-29T12:00', '2025-07-29T14:55',
    NULL, NULL, NULL, 3304.447999966785, 1.05, 3469.6703999651245,
    4.295830722648046, 1, 0
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'TK'),
    '638', '2025-07-29',
    (SELECT id FROM atlas_airports WHERE iata_code = 'NBO'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'IST'),
    NULL, NULL, NULL, '2025-07-29T03:35', '2025-07-29T10:25',
    NULL, NULL, NULL, 4806.401489595088, 1.05, 5046.721564074843,
    6.151185033365361, 1, 0
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'EK'),
    '719', '2025-07-20',
    (SELECT id FROM atlas_airports WHERE iata_code = 'DXB'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'NBO'),
    NULL, NULL, NULL, '2025-07-20T10:30', '2025-07-20T14:30',
    NULL, NULL, NULL, 3559.2484182497565, 1.05, 3737.2108391622446,
    4.6105841805270105, 1, 0
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = '3U'),
    '3917', '2025-07-19',
    (SELECT id FROM atlas_airports WHERE iata_code = 'TFU'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'DXB'),
    NULL, NULL, NULL, '2025-07-19T16:55', '2025-07-19T20:20',
    NULL, NULL, NULL, 4824.071344401572, 1.05, 5065.274911621651,
    6.173012501067489, 1, 0
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'QR'),
    '870', '2025-07-13',
    (SELECT id FROM atlas_airports WHERE iata_code = 'DOH'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'PVG'),
    NULL, NULL, NULL, '2025-07-13T02:15', '2025-07-13T16:20',
    NULL, NULL, NULL, 6796.008304777071, 1.03, 6999.888553920384,
    8.449028550830704, 1, 0
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'QR'),
    '56', '2025-07-12',
    (SELECT id FROM atlas_airports WHERE iata_code = 'NCE'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'DOH'),
    NULL, NULL, NULL, '2025-07-12T15:55', '2025-07-12T22:45',
    NULL, NULL, NULL, 4485.561538275718, 1.05, 4709.839615189504,
    5.754853328794375, 1, 0
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'QR'),
    '55', '2025-06-29',
    (SELECT id FROM atlas_airports WHERE iata_code = 'DOH'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'NCE'),
    NULL, NULL, NULL, '2025-06-29T08:50', '2025-06-29T14:10',
    NULL, NULL, NULL, 4485.561538275718, 1.05, 4709.839615189504,
    5.754853328794375, 1, 0
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'QR'),
    '871', '2025-06-29',
    (SELECT id FROM atlas_airports WHERE iata_code = 'PVG'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'DOH'),
    NULL, NULL, NULL, '2025-06-29T00:35', '2025-06-29T04:45',
    NULL, NULL, NULL, 6796.008304777071, 1.03, 6999.888553920384,
    8.449028550830704, 1, 0
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'MU'),
    '596', '2024-08-22',
    (SELECT id FROM atlas_airports WHERE iata_code = 'HKG'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'HGH'),
    NULL, NULL, NULL, '2024-08-22T17:00', '2024-08-22T19:35',
    NULL, NULL, NULL, 1094.0706948333232, 1.08, 1181.596350419989,
    1.5237090720285558, 1, 0
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'CX'),
    '391', '2024-08-19',
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'HKG'),
    NULL, NULL, NULL, '2024-08-19T13:40', '2024-08-19T17:25',
    NULL, NULL, NULL, 1991.5621693034213, 1.05, 2091.1402777685926,
    2.67403057888742, 1, 0
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'CA'),
    '872', '2024-08-05',
    (SELECT id FROM atlas_airports WHERE iata_code = 'KUL'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    NULL, NULL, NULL, '2024-08-05T01:45', '2024-08-05T08:10',
    NULL, NULL, NULL, 4413.601044035894, 1.05, 4634.281096237689,
    5.6659609535569455, 1, 0
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'MH'),
    '1058', '2024-08-01',
    (SELECT id FROM atlas_airports WHERE iata_code = 'JHB'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'KUL'),
    NULL, NULL, NULL, '2024-08-01T19:45', '2024-08-01T20:45',
    NULL, NULL, NULL, 249.9826920041703, 1.12, 279.98061504467074,
    0.4179883690268024, 1, 0
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'AK'),
    '6035', '2024-08-01',
    (SELECT id FROM atlas_airports WHERE iata_code = 'JHB'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'KUL'),
    NULL, NULL, NULL, '2024-08-01T13:50', '2024-08-01T14:45',
    NULL, NULL, NULL, 249.9826920041703, 1.12, 279.98061504467074,
    0.4179883690268024, 1, 0
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'GA'),
    '828', '2024-07-28',
    (SELECT id FROM atlas_airports WHERE iata_code = 'CGK'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'SIN'),
    NULL, NULL, NULL, '2024-07-28T08:35', '2024-07-28T11:20',
    NULL, NULL, NULL, 883.8206424316695, 1.08, 954.5262938262032,
    1.199323276894576, 1, 0
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'CX'),
    '797', '2024-06-29',
    (SELECT id FROM atlas_airports WHERE iata_code = 'HKG'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'CGK'),
    NULL, NULL, NULL, '2024-06-29T19:05', '2024-06-29T22:55',
    NULL, NULL, NULL, 3259.3707283085423, 1.05, 3422.33926472397,
    4.24014703412904, 1, 0
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'CX'),
    '391', '2024-06-29',
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'HKG'),
    NULL, NULL, NULL, '2024-06-29T13:40', '2024-06-29T17:25',
    NULL, NULL, NULL, 1991.5621693034213, 1.05, 2091.1402777685926,
    2.67403057888742, 1, 0
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'MU'),
    '898', '2024-02-24',
    (SELECT id FROM atlas_airports WHERE iata_code = 'SIN'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'HGH'),
    NULL, NULL, NULL, '2024-02-24T03:30', '2024-02-24T08:20',
    NULL, NULL, NULL, 3649.122784050196, 1.05, 3831.578923252706,
    4.721605455927554, 1, 0
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'GA'),
    '828', '2024-02-17',
    (SELECT id FROM atlas_airports WHERE iata_code = 'CGK'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'SIN'),
    NULL, NULL, NULL, '2024-02-17T07:25', '2024-02-17T10:10',
    NULL, NULL, NULL, 883.8206424316695, 1.08, 954.5262938262032,
    1.199323276894576, 1, 0
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'GA'),
    '425', '2024-02-12',
    (SELECT id FROM atlas_airports WHERE iata_code = 'DPS'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'CGK'),
    NULL, NULL, NULL, '2024-02-12T20:15', '2024-02-12T21:15',
    NULL, NULL, NULL, 982.6231972869821, 1.08, 1061.2330530699408,
    1.3517615043856297, 1, 0
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'GA'),
    '416', '2024-02-08',
    (SELECT id FROM atlas_airports WHERE iata_code = 'CGK'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'DPS'),
    NULL, NULL, NULL, '2024-02-08T18:45', '2024-02-08T21:40',
    NULL, NULL, NULL, 982.6231972869821, 1.08, 1061.2330530699408,
    1.3517615043856297, 1, 0
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'CA'),
    '977', '2024-02-07',
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'CGK'),
    NULL, NULL, NULL, '2024-02-07T14:30', '2024-02-07T21:15',
    NULL, NULL, NULL, 5237.611068114117, 1.03, 5394.739400157541,
    6.560617781697948, 1, 0
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'CZ'),
    '388', '2023-07-26',
    (SELECT id FROM atlas_airports WHERE iata_code = 'CGK'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'CAN'),
    NULL, NULL, NULL, '2023-07-26T09:10', '2023-07-26T15:30',
    NULL, NULL, NULL, 3360.6339953191246, 1.05, 3528.665695085081,
    4.365236952200936, 1, 0
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'OZ'),
    '761', '2023-07-14',
    (SELECT id FROM atlas_airports WHERE iata_code = 'ICN'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'CGK'),
    NULL, NULL, NULL, '2023-07-14T15:20', '2023-07-14T20:20',
    NULL, NULL, NULL, 5263.0417747427955, 1.03, 5420.933027985079,
    6.591433814436228, 1, 0
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'OZ'),
    '332', '2023-07-14',
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'ICN'),
    NULL, NULL, NULL, '2023-07-14T10:40', '2023-07-14T13:50',
    NULL, NULL, NULL, 901.0960797941704, 1.08, 973.183766177704,
    1.2259768088252914, 1, 0
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'CZ'),
    '388', '2023-01-28',
    (SELECT id FROM atlas_airports WHERE iata_code = 'CGK'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'CAN'),
    NULL, NULL, NULL, '2023-01-28T23:30', '2023-01-29T05:00',
    NULL, NULL, NULL, 3360.6339953191246, 1.05, 3528.665695085081,
    4.365236952200936, 1, 0
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'CZ'),
    '387', '2023-01-14',
    (SELECT id FROM atlas_airports WHERE iata_code = 'CAN'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'CGK'),
    NULL, NULL, NULL, '2023-01-14T18:20', '2023-01-14T22:20',
    NULL, NULL, NULL, 3360.6339953191246, 1.05, 3528.665695085081,
    4.365236952200936, 1, 0
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'CZ'),
    '388', '2019-10-07',
    (SELECT id FROM atlas_airports WHERE iata_code = 'CGK'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'CAN'),
    NULL, NULL, NULL, '2019-10-07T09:05', '2019-10-07T15:30',
    NULL, NULL, NULL, 3360.6339953191246, 1.05, 3528.665695085081,
    4.365236952200936, 1, 0
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'CZ'),
    '8353', '2019-09-30',
    (SELECT id FROM atlas_airports WHERE iata_code = 'SZX'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'CGK'),
    NULL, NULL, NULL, '2019-09-30T19:05', '2019-09-30T23:00',
    NULL, NULL, NULL, 3291.704721016759, 1.05, 3456.289957067597,
    4.280089025121542, 1, 0
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'AF'),
    '1404', '2019-08-14',
    (SELECT id FROM atlas_airports WHERE iata_code = 'CDG'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'FCO'),
    NULL, NULL, NULL, '2019-08-14T17:05', '2019-08-14T19:10',
    NULL, NULL, NULL, 1100.5705489036206, 1.08, 1188.6161928159104,
    1.5337374183084433, 1, 0
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'AF'),
    '128', '2019-07-27',
    (SELECT id FROM atlas_airports WHERE iata_code = 'CDG'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    NULL, NULL, NULL, '2019-07-27T13:40', '2019-07-28T05:55',
    NULL, NULL, NULL, 8189.965277574113, 1.03, 8435.664235901337,
    10.138176411984766, 1, 0
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'AF'),
    '125', '2019-07-14',
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'CDG'),
    NULL, NULL, NULL, '2019-07-14T09:05', '2019-07-14T13:55',
    NULL, NULL, NULL, 8189.965277574113, 1.03, 8435.664235901337,
    10.138176411984766, 1, 0
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'CA'),
    '978', '2019-02-14',
    (SELECT id FROM atlas_airports WHERE iata_code = 'CGK'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    NULL, NULL, NULL, '2019-02-14T22:45', '2019-02-15T07:00',
    NULL, NULL, NULL, 5237.611068114117, 1.03, 5394.739400157541,
    6.560617781697948, 1, 0
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'CA'),
    '977', '2019-02-03',
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'CGK'),
    NULL, NULL, NULL, '2019-02-03T14:55', '2019-02-03T21:15',
    NULL, NULL, NULL, 5237.611068114117, 1.03, 5394.739400157541,
    6.560617781697948, 1, 0
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'AA'),
    '187', '2018-08-02',
    (SELECT id FROM atlas_airports WHERE iata_code = 'ORD'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    NULL, NULL, NULL, '2018-08-02T18:00', '2018-08-02T20:20',
    NULL, NULL, NULL, 10562.827931102576, 1.03, 10879.712769035654,
    13.013527627436904, 1, 0
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'AA'),
    '186', '2018-07-20',
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'ORD'),
    NULL, NULL, NULL, '2018-07-20T10:10', '2018-07-21T10:00',
    NULL, NULL, NULL, 10562.827931102576, 1.03, 10879.712769035654,
    13.013527627436904, 1, 0
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'GA'),
    '890', '2017-08-03',
    (SELECT id FROM atlas_airports WHERE iata_code = 'CGK'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    NULL, NULL, NULL, '2017-08-03T22:45', '2017-08-04T06:55',
    NULL, NULL, NULL, 5237.611068114117, 1.03, 5394.739400157541,
    6.560617781697948, 1, 0
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'KA'),
    '901', '2017-07-09',
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'HKG'),
    NULL, NULL, NULL, '2017-07-09T12:30', '2017-07-09T16:15',
    NULL, NULL, NULL, 1991.5621693034213, 1.05, 2091.1402777685926,
    2.67403057888742, 1, 0
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'KA'),
    '974', '2016-08-28',
    (SELECT id FROM atlas_airports WHERE iata_code = 'HKG'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    NULL, NULL, NULL, '2016-08-28T16:00', '2016-08-28T19:15',
    NULL, NULL, NULL, 1991.5621693034213, 1.05, 2091.1402777685926,
    2.67403057888742, 1, 0
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'CX'),
    '347', '2016-07-30',
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'HKG'),
    NULL, NULL, NULL, '2016-07-30T10:00', '2016-07-30T13:50',
    NULL, NULL, NULL, 1991.5621693034213, 1.05, 2091.1402777685926,
    2.67403057888742, 1, 0
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'CA'),
    '862', '2015-07-23',
    (SELECT id FROM atlas_airports WHERE iata_code = 'GVA'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    NULL, NULL, NULL, '2015-07-23T20:25', '2015-07-24T12:50',
    NULL, NULL, NULL, 8201.214579214255, 1.03, 8447.251016590682,
    10.151807918678113, 1, 0
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'CA'),
    '961', '2015-07-10',
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'MUC'),
    NULL, NULL, NULL, '2015-07-10T01:10', '2015-07-10T05:30',
    NULL, NULL, NULL, 7721.829235115377, 1.03, 7953.484112168839,
    9.570905678181827, 1, 0
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'KA'),
    '974', '2015-02-28',
    (SELECT id FROM atlas_airports WHERE iata_code = 'HKG'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    NULL, NULL, NULL, '2015-02-28T16:50', '2015-02-28T20:10',
    NULL, NULL, NULL, 1991.5621693034213, 1.05, 2091.1402777685926,
    2.67403057888742, 1, 0
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'KA'),
    '901', '2015-02-08',
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'HKG'),
    NULL, NULL, NULL, '2015-02-08T12:30', '2015-02-08T16:10',
    NULL, NULL, NULL, 1991.5621693034213, 1.05, 2091.1402777685926,
    2.67403057888742, 1, 0
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'CX'),
    '312', '2014-08-22',
    (SELECT id FROM atlas_airports WHERE iata_code = 'HKG'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    NULL, NULL, NULL, '2014-08-22T17:00', '2014-08-22T20:25',
    NULL, NULL, NULL, 1991.5621693034213, 1.05, 2091.1402777685926,
    2.67403057888742, 1, 0
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'CX'),
    '347', '2014-07-13',
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'HKG'),
    NULL, NULL, NULL, '2014-07-13T10:00', '2014-07-13T13:50',
    NULL, NULL, NULL, 1991.5621693034213, 1.05, 2091.1402777685926,
    2.67403057888742, 1, 0
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'CZ'),
    '318', '2014-01-26',
    (SELECT id FROM atlas_airports WHERE iata_code = 'GMP'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    NULL, NULL, NULL, '2014-01-26T12:30', '2014-01-26T13:35',
    NULL, NULL, NULL, 925.8858144296134, 1.08, 999.9566795839826,
    1.2642238279771179, 1, 0
  ),
  (
    (SELECT id FROM atlas_airlines WHERE iata_code = 'CZ'),
    '317', '2014-01-22',
    (SELECT id FROM atlas_airports WHERE iata_code = 'PEK'),
    (SELECT id FROM atlas_airports WHERE iata_code = 'GMP'),
    NULL, NULL, NULL, '2014-01-22T08:20', '2014-01-22T11:30',
    NULL, NULL, NULL, 925.8858144296134, 1.08, 999.9566795839826,
    1.2642238279771179, 1, 0
  )
ON CONFLICT(airline_id, flight_number, flight_date, departure_airport_id, arrival_airport_id) DO UPDATE SET
  scheduled_departure_local = excluded.scheduled_departure_local,
  scheduled_arrival_local = excluded.scheduled_arrival_local,
  great_circle_km = excluded.great_circle_km,
  route_factor = excluded.route_factor,
  route_distance_km = excluded.route_distance_km,
  estimated_hours = excluded.estimated_hours,
  formula_version = excluded.formula_version,
  is_domestic = excluded.is_domestic,
  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now');
